---
title: "Lobsters"
author: "Alicia Fennell and Rachel Rhodes"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Introduction 

# Data and Methods

# Results

```{r}

# Attach packages and read in lobster data

library(tidyverse)
library(here)
library(janitor)
library(tidyr)
library(ggridges)
library(directlabels)
library(RColorBrewer)

```

## Results A
### Changes in annual lobster abundance by site 


```{r}

## Creating tidy data

lobster_ab <- read_csv("lobster_abundance_sbc_lter.csv", na = "-99999") %>% 
  clean_names()

lobster_tidy <- lobster_ab %>% 
  uncount(count) %>% 
  mutate(site = replace(site, site == "IVEE", "Isla Vista")) %>%
  mutate(site = replace(site, site == "CARP", "Carpinteria")) %>% 
  mutate(site = replace(site, site == "AQUE", "Arroyo Quemado")) %>% 
  mutate(site = replace(site, site == "MOHK", "Mohawk")) %>% 
  mutate(site = replace(site, site == "NAPL", "Naples")) %>% 
  mutate(site_type = if_else(site %in% c("Isla Vista","Naples"), "MPA", "Non-MPA"))

annual_ab_site <- lobster_tidy %>% 
  group_by(year) %>% 
  count(site) %>% 
  mutate(site_type = if_else(site %in% c("Isla Vista","Naples"), "MPA", "Non-MPA"))

lobster_summaries <- lobster_tidy %>% 
  group_by(year, site_type) %>% 
  filter(year == c(2012, 2018)) %>% 
  summarize(mean_size = mean(size_mm), sd_size = sd(size_mm))
  
year_2012 <- lobster_tidy %>% 
  filter(year == "2012")

         
```

```{r}

## Exploratory graphs


# ggplot(annual_ab_site, aes(x = year, y = n)) +
#   geom_line(aes(color = site)) +
#   theme_minimal()
# 
# ggplot(annual_ab_site, aes(x = year, y = n)) +
#   geom_bar(stat = "identity") +
#   facet_wrap(~site) +
#   theme_minimal() 

```


```{r}

## Results A - visualalization showing  changes in annual lobster abundace at the five sites over time, designating MPA versus non-MPA sites. 

ggplot(annual_ab_site, aes(x = year, y = n)) +
  geom_line(aes(group = site,
                color = site_type), 
            size = 0.75) +
  scale_color_manual(values = c("coral2", "deepskyblue3"))+
  theme_minimal()+
  theme(
    legend.position = c(0.25, .88),
    legend.justification = c("right", "top"),
    legend.box.just = "right",
    legend.margin = margin(6, 6, 6, 6),
    legend.background = element_rect("white"))+
  xlim(2012,2019.5) +
  geom_dl(aes(label=site,
              color = site_type),
          method = "last.points") +
  ggtitle("CALIFORNIA SPINY LOBSTER ABUNDANCE",
          subtitle = "Santa Barbara Channel (2012 - 2018)")+
  labs(x = "Year",
       y = "Lobster count",
       color = "Site Type")
```

## Results B
### Lobster size distribution shifts between 2012 and 2018


```{r}
## Data frame for exploring lobster size dstirbution shifts in 2012 and 2018

lobster_size <- lobster_tidy %>% 
  filter(year == c(2012, 2018))

```

```{r}
## Results B - Visualization of size distribution for lobsters obvserved at the 5 different sites in 2012 and 2018. Graph shows the community size distributions at each int eh 2 yers. 

ggplot(lobster_size, aes(x = site, y = size_mm, fill = factor(year))) +
  geom_violin(time = FALSE)+
  scale_fill_brewer()+
  labs(x = "Site",
       y = "Size (mm)",
       fill = "Year")+
  ggtitle("CALIFORNIA SPINY LOBSTER DISTRIBUTION 2012 & 2018",
          subtitle = "Santa Barbara Channel")+
  theme_minimal()+
  theme(legend.position = c(0.78, .88),
        legend.justification = c("left", "top"),
        legend.box.just = "right",
        legend.margin = margin(6, 6, 6, 6),
        legend.background = element_rect("white"))
  


```
```{r}
ggplot(lobster_size, aes(x = site, y = size_mm, fill = factor(year))) +
  geom_jitter(aes(group = factor(year),
                  color = factor(year)))
```

## Results C
### Mean lobster sizes between site types (MPA and non-MPA) in 2012 and 2018


```{r}
## Starting t tests

lobs_2012 <- lobster_summaries %>% 
  filter(year == "2012")

MPA_2012 <- lobster_tidy %>% 
  filter(year == "2012") %>% 
  filter(site_type == "MPA") %>% 
  pull(size_mm)

MPA_2012

non_MPA_2012 <- lobster_tidy %>% 
  filter(year == "2012") %>% 
  filter(site_type == "Non-MPA") %>% 
  pull(size_mm)

size_2012_ttest <- t.test(MPA_2012, non_MPA_2012)

size_2012_ttest

test_meann <- lobster_tidy %>% 
  filter(year == "2012") %>% 
  filter(site_type == "Non-MPA") %>% 
  summarise(mean_size = mean(size_mm))
  
MPA_test <- year_2012 %>% 
  filter(site_type == "MPA") %>% 
  pull(size_mm)


non_MPA_test <- year_2012 %>% 
  filter(site_type == "Non-MPA") %>% 
  pull(size_mm)

size_test <- t.test(MPA_test, non_MPA_test)

size_test

```

# Summary 

# References 